WITH TRIPS AS (

select
RIDE_ID,
RIDEABLE_TYPE,
DATE(TO_TIMESTAMP(STARTED_AT)) AS TRIP_DATE,
START_STATIO_ID AS START_STATION_ID,
END_STATION_ID,
MEMBER_CSUAL AS MEMBER_CASUAL,
TIMESTAMPDIFF(SECOND,TO_TIMESTAMP(ENDED_AT),TO_TIMESTAMP(STARTED_AT))


from {{ source('demo', 'bike') }}
where ride_id != 'ride_id'


)

select 
* 
from TRIPS